// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shelter.Database;

namespace Shelter.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181027152251_AddCommentsAndQuest1")]
    partial class AddCommentsAndQuest1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Shelter.Entity.Comment", b =>
                {
                    b.Property<Guid>("CommentGuid");

                    b.Property<DateTimeOffset>("CratedDate");

                    b.Property<Guid>("QuestionnaireGuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("UserGuid");

                    b.HasKey("CommentGuid");

                    b.HasIndex("QuestionnaireGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Shelter.Entity.Questionnaire", b =>
                {
                    b.Property<Guid>("QuestionnaireGuid");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Old");

                    b.Property<string>("Race")
                        .IsRequired();

                    b.Property<string>("Sex")
                        .IsRequired();

                    b.Property<Guid>("UserGuid");

                    b.Property<string>("Vaccination");

                    b.HasKey("QuestionnaireGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Shelter.Entity.Role", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Shelter.Entity.User", b =>
                {
                    b.Property<Guid>("UserGuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("RoleId");

                    b.HasKey("UserGuid");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shelter.Entity.Comment", b =>
                {
                    b.HasOne("Shelter.Entity.Questionnaire", "Questionnaire")
                        .WithMany("Comments")
                        .HasForeignKey("QuestionnaireGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Shelter.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shelter.Entity.Questionnaire", b =>
                {
                    b.HasOne("Shelter.Entity.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Shelter.Entity.User", b =>
                {
                    b.HasOne("Shelter.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
